import type { ProductAliasRule } from './product-merge'

// High-confidence duplicate-product merges found by a full-catalog scan
// (2026-09-02, see git history of SESSION_RESUME.md for the analysis
// prompt and methodology - Opus judged all 8,695 product rows against the
// existing CANONICAL_BASE_MODEL map in catalog's products.ts
// and flagged rows that split the same real product purely from
// inconsistent extraction: variant text landing in base_model instead of
// variant_tier, brand-prefix inconsistency, spelling/spacing, doubled tier,
// bogus 5G/4G tier on single-radio-only models). Deliberately excludes the
// scan's own "medium confidence" and "false-positive risk" items (GPS vs
// cellular, screen-size-as-variant, generic plural buckets like Bag/Bags,
// genuine trailing-s model numbers like iPhone 6 vs 6s) - those need a human
// call, not a blind merge.
export const PRODUCT_VARIANT_ALIAS_RULES: ProductAliasRule[] = [
  // ---- Apple: iPhone ----
  { aliasBase: 'iPhone 11 Pro', aliasVariant: null, canonicalBase: 'iPhone 11', canonicalVariant: 'Pro' },
  { aliasBase: 'iPhone 11 Pro', aliasVariant: 'Pro', canonicalBase: 'iPhone 11', canonicalVariant: 'Pro' },
  { aliasBase: 'iPhone 11 Pro Max', aliasVariant: null, canonicalBase: 'iPhone 11', canonicalVariant: 'Pro Max' },
  { aliasBase: 'iPhone 12 Pro', aliasVariant: null, canonicalBase: 'iPhone 12', canonicalVariant: 'Pro' },
  { aliasBase: 'iPhone 12 mini', aliasVariant: null, canonicalBase: 'iPhone 12', canonicalVariant: 'Mini' },
  { aliasBase: 'iPhone 14 Plus', aliasVariant: null, canonicalBase: 'iPhone 14', canonicalVariant: 'Plus' },
  { aliasBase: 'iPhone 14 Pro', aliasVariant: null, canonicalBase: 'iPhone 14', canonicalVariant: 'Pro' },
  { aliasBase: 'iPhone', aliasVariant: '14 Pro Max', canonicalBase: 'iPhone 14', canonicalVariant: 'Pro Max' },
  { aliasBase: 'iPhone 15 Plus', aliasVariant: null, canonicalBase: 'iPhone 15', canonicalVariant: 'Plus' },
  { aliasBase: 'iPhone 16 Plus', aliasVariant: null, canonicalBase: 'iPhone 16', canonicalVariant: 'Plus' },
  { aliasBase: 'iPhone 6 Plus', aliasVariant: null, canonicalBase: 'iPhone 6', canonicalVariant: 'Plus' },
  { aliasBase: 'iPhone 6s Plus', aliasVariant: null, canonicalBase: 'iPhone 6s', canonicalVariant: 'Plus' },
  { aliasBase: 'iPhone 7 Plus', aliasVariant: null, canonicalBase: 'iPhone 7', canonicalVariant: 'Plus' },
  { aliasBase: 'iPhone 7 Plus', aliasVariant: 'Plus', canonicalBase: 'iPhone 7', canonicalVariant: 'Plus' },
  { aliasBase: 'iPhone 8 Plus', aliasVariant: null, canonicalBase: 'iPhone 8', canonicalVariant: 'Plus' },
  { aliasBase: 'iPhone XS Max', aliasVariant: null, canonicalBase: 'iPhone XS', canonicalVariant: 'Max' },
  { aliasBase: 'iPhone XS', aliasVariant: 'Maxx', canonicalBase: 'iPhone XS', canonicalVariant: 'Max' },
  { aliasBase: 'iPhone', aliasVariant: '11', canonicalBase: 'iPhone 11', canonicalVariant: null },
  { aliasBase: 'iPhone', aliasVariant: '12', canonicalBase: 'iPhone 12', canonicalVariant: null },
  { aliasBase: 'iPhone', aliasVariant: '15', canonicalBase: 'iPhone 15', canonicalVariant: null },
  { aliasBase: 'iPhone SE', aliasVariant: '2020', canonicalBase: 'iPhone SE', canonicalVariant: '2nd Gen' },

  // ---- Apple: iPad ----
  { aliasBase: 'iPad 10th Gen', aliasVariant: null, canonicalBase: 'iPad', canonicalVariant: '10th Gen' },
  { aliasBase: 'iPad 11th Gen', aliasVariant: null, canonicalBase: 'iPad', canonicalVariant: '11th Gen' },
  { aliasBase: 'iPad 6th Gen', aliasVariant: null, canonicalBase: 'iPad', canonicalVariant: '6th Gen' },
  { aliasBase: 'iPad 7th Gen', aliasVariant: null, canonicalBase: 'iPad', canonicalVariant: '7th Gen' },
  { aliasBase: 'iPad 8th Gen', aliasVariant: null, canonicalBase: 'iPad', canonicalVariant: '8th Gen' },
  { aliasBase: 'iPad 9th Gen', aliasVariant: null, canonicalBase: 'iPad', canonicalVariant: '9th Gen' },
  { aliasBase: 'iPad 9th Generation', aliasVariant: null, canonicalBase: 'iPad', canonicalVariant: '9th Gen' },
  { aliasBase: 'iPad', aliasVariant: '9th Generation', canonicalBase: 'iPad', canonicalVariant: '9th Gen' },
  { aliasBase: 'iPad A16', aliasVariant: null, canonicalBase: 'iPad', canonicalVariant: '11th Gen' },
  { aliasBase: 'iPad', aliasVariant: '6th Generation', canonicalBase: 'iPad', canonicalVariant: '6th Gen' },
  { aliasBase: 'iPad', aliasVariant: 'Pro', canonicalBase: 'iPad Pro', canonicalVariant: null },
  { aliasBase: 'iPad Air 2', aliasVariant: null, canonicalBase: 'iPad Air', canonicalVariant: '2' },
  { aliasBase: 'iPad Mini 3', aliasVariant: null, canonicalBase: 'iPad Mini', canonicalVariant: '3' },
  { aliasBase: 'iPad Mini 4', aliasVariant: null, canonicalBase: 'iPad Mini', canonicalVariant: '4' },
  { aliasBase: 'iPad Mini 5', aliasVariant: null, canonicalBase: 'iPad Mini', canonicalVariant: '5' },
  { aliasBase: 'iPad mini 6', aliasVariant: null, canonicalBase: 'iPad Mini', canonicalVariant: '6th Gen' },
  { aliasBase: 'iPad Air M3', aliasVariant: null, canonicalBase: 'iPad Air', canonicalVariant: 'M3' },
  { aliasBase: 'iPad Air M4', aliasVariant: null, canonicalBase: 'iPad Air', canonicalVariant: 'M4' },
  { aliasBase: 'iPad Air', aliasVariant: '5th Gen M1', canonicalBase: 'iPad Air', canonicalVariant: '5th Gen' },
  { aliasBase: 'iPad Air', aliasVariant: '5th Generation', canonicalBase: 'iPad Air', canonicalVariant: '5th Gen' },
  { aliasBase: 'iPad Mini 7', aliasVariant: 'A17 Pro', canonicalBase: 'iPad Mini', canonicalVariant: '7' },
  {
    aliasBase: 'iPad Pro 12.9',
    aliasVariant: '5th Generation',
    canonicalBase: 'iPad Pro 12.9',
    canonicalVariant: '5th Gen',
  },
  { aliasBase: 'iPad Pro', aliasVariant: '12.9 3rd Gen', canonicalBase: 'iPad Pro 12.9', canonicalVariant: '3rd Gen' },

  // ---- Apple: Mac / Watch / accessories ----
  { aliasBase: 'MacBook Air M1', aliasVariant: null, canonicalBase: 'MacBook Air', canonicalVariant: 'M1' },
  { aliasBase: 'MacBook Air', aliasVariant: 'M1 2020', canonicalBase: 'MacBook Air', canonicalVariant: 'M1' },
  { aliasBase: 'MacBook Air M2', aliasVariant: null, canonicalBase: 'MacBook Air', canonicalVariant: 'M2' },
  { aliasBase: 'MacBook Air M3', aliasVariant: null, canonicalBase: 'MacBook Air', canonicalVariant: 'M3' },
  { aliasBase: 'MacBook Air M4', aliasVariant: null, canonicalBase: 'MacBook Air', canonicalVariant: 'M4' },
  { aliasBase: 'MacBook Air', aliasVariant: 'M4 13-inch', canonicalBase: 'MacBook Air', canonicalVariant: 'M4' },
  { aliasBase: 'MacBook Air M4 13 inch', aliasVariant: null, canonicalBase: 'MacBook Air', canonicalVariant: 'M4' },
  { aliasBase: 'MacBook Air M5', aliasVariant: null, canonicalBase: 'MacBook Air', canonicalVariant: 'M5' },
  { aliasBase: 'MacBook Air', aliasVariant: 'M5 13-inch', canonicalBase: 'MacBook Air', canonicalVariant: 'M5' },
  { aliasBase: 'MacBook Pro 2020', aliasVariant: null, canonicalBase: 'MacBook Pro', canonicalVariant: '2020' },
  { aliasBase: 'Apple MacBook Pro M1', aliasVariant: null, canonicalBase: 'MacBook Pro M1', canonicalVariant: null },
  { aliasBase: 'Apple iMac', aliasVariant: null, canonicalBase: 'iMac', canonicalVariant: null },
  { aliasBase: 'Mac Mini M2', aliasVariant: null, canonicalBase: 'Mac mini', canonicalVariant: 'M2' },
  { aliasBase: 'MacBook Pro', aliasVariant: 'NEO', canonicalBase: 'MacBook Neo', canonicalVariant: null },
  { aliasBase: 'MacBook', aliasVariant: 'Neo', canonicalBase: 'MacBook Neo', canonicalVariant: null },
  {
    aliasBase: 'Apple Pencil',
    aliasVariant: '2nd Generation',
    canonicalBase: 'Apple Pencil',
    canonicalVariant: '2nd Gen',
  },
  {
    aliasBase: 'Apple Pencil',
    aliasVariant: '1st Generation',
    canonicalBase: 'Apple Pencil',
    canonicalVariant: 'Gen 1',
  },
  { aliasBase: 'Apple AirPods', aliasVariant: 'Max', canonicalBase: 'AirPods Max', canonicalVariant: null },
  { aliasBase: 'Apple AirPods Max', aliasVariant: null, canonicalBase: 'AirPods Max', canonicalVariant: null },
  { aliasBase: 'Airpods Pro 2', aliasVariant: null, canonicalBase: 'AirPods Pro', canonicalVariant: '2nd Generation' },
  {
    aliasBase: 'Apple AirPods Pro',
    aliasVariant: '2',
    canonicalBase: 'AirPods Pro',
    canonicalVariant: '2nd Generation',
  },
  {
    aliasBase: 'Apple AirPods Pro',
    aliasVariant: '2nd Gen',
    canonicalBase: 'AirPods Pro',
    canonicalVariant: '2nd Generation',
  },
  { aliasBase: 'Airpods', aliasVariant: 'Pro 3', canonicalBase: 'AirPods Pro', canonicalVariant: '3' },
  { aliasBase: 'Apple AirPods 4', aliasVariant: null, canonicalBase: 'AirPods 4', canonicalVariant: null },
  { aliasBase: 'Apple EarPods', aliasVariant: null, canonicalBase: 'Earpods', canonicalVariant: null },
  { aliasBase: 'Apple Watch', aliasVariant: 'Series 9', canonicalBase: 'Apple Watch Series 9', canonicalVariant: null },
  {
    aliasBase: 'Apple Watch',
    aliasVariant: 'Series 10',
    canonicalBase: 'Apple Watch Series 10',
    canonicalVariant: null,
  },
  {
    aliasBase: 'Apple Watch SE 2nd Gen',
    aliasVariant: null,
    canonicalBase: 'Apple Watch SE',
    canonicalVariant: '2nd Gen',
  },
  {
    aliasBase: 'Apple iPad Magic Keyboard',
    aliasVariant: '11-inch',
    canonicalBase: 'Apple iPad Magic Keyboard',
    canonicalVariant: null,
  },
  {
    aliasBase: 'Apple iPad Smart Keyboard',
    aliasVariant: null,
    canonicalBase: 'iPad Smart Keyboard',
    canonicalVariant: null,
  },

  // ---- Samsung ----
  { aliasBase: 'Galaxy S23 Ultra', aliasVariant: null, canonicalBase: 'Samsung Galaxy S23', canonicalVariant: 'Ultra' },
  { aliasBase: 'Galaxy Z Flip5', aliasVariant: null, canonicalBase: 'Samsung Galaxy Z Flip 5', canonicalVariant: null },
  { aliasBase: 'Galaxy Z Flip7', aliasVariant: null, canonicalBase: 'Samsung Galaxy Z Flip 7', canonicalVariant: null },
  { aliasBase: 'Samsung Flip 7', aliasVariant: null, canonicalBase: 'Samsung Galaxy Z Flip 7', canonicalVariant: null },
  {
    aliasBase: 'Samsung Galaxy Z Fold4',
    aliasVariant: null,
    canonicalBase: 'Samsung Galaxy Z Fold 4',
    canonicalVariant: null,
  },
  {
    aliasBase: 'Samsung Galaxy Watch5',
    aliasVariant: 'Pro',
    canonicalBase: 'Samsung Galaxy Watch 5',
    canonicalVariant: 'Pro',
  },
  {
    aliasBase: 'Samsung Galaxy Fit3',
    aliasVariant: null,
    canonicalBase: 'Samsung Galaxy Fit 3',
    canonicalVariant: null,
  },
  {
    aliasBase: 'Samsung Galaxy Z Flip6',
    aliasVariant: '5G',
    canonicalBase: 'Samsung Galaxy Z Flip 6',
    canonicalVariant: null,
  },
  {
    aliasBase: 'Samsung Galaxy Watch Ultra',
    aliasVariant: null,
    canonicalBase: 'Samsung Galaxy Watch',
    canonicalVariant: 'Ultra',
  },
  {
    aliasBase: 'Samsung Galaxy S25 Ultra',
    aliasVariant: 'Ultra',
    canonicalBase: 'Samsung Galaxy S25',
    canonicalVariant: 'Ultra',
  },
  {
    aliasBase: 'Samsung S26 Ultra',
    aliasVariant: 'Ultra',
    canonicalBase: 'Samsung Galaxy S26',
    canonicalVariant: 'Ultra',
  },
  {
    aliasBase: 'Samsung Galaxy S23 FE',
    aliasVariant: 'FE',
    canonicalBase: 'Samsung Galaxy S23',
    canonicalVariant: 'FE',
  },
  { aliasBase: 'Samsung A03s', aliasVariant: null, canonicalBase: 'Samsung Galaxy A03s', canonicalVariant: null },
  { aliasBase: 'Samsung A05', aliasVariant: null, canonicalBase: 'Samsung Galaxy A05', canonicalVariant: null },
  { aliasBase: 'Samsung A05S', aliasVariant: null, canonicalBase: 'Samsung Galaxy A05s', canonicalVariant: null },
  { aliasBase: 'Samsung A12', aliasVariant: null, canonicalBase: 'Samsung Galaxy A12', canonicalVariant: null },
  { aliasBase: 'Samsung A27', aliasVariant: null, canonicalBase: 'Samsung Galaxy A27', canonicalVariant: null },
  { aliasBase: 'Samsung A34', aliasVariant: null, canonicalBase: 'Samsung Galaxy A34', canonicalVariant: null },
  { aliasBase: 'Samsung A53', aliasVariant: null, canonicalBase: 'Samsung Galaxy A53', canonicalVariant: null },
  { aliasBase: 'Samsung A56', aliasVariant: null, canonicalBase: 'Samsung Galaxy A56', canonicalVariant: null },
  { aliasBase: 'Samsung A71', aliasVariant: null, canonicalBase: 'Samsung Galaxy A71', canonicalVariant: null },
  { aliasBase: 'Samsung A06', aliasVariant: null, canonicalBase: 'Samsung Galaxy A06', canonicalVariant: null },
  { aliasBase: 'Samsung S20 FE', aliasVariant: null, canonicalBase: 'Samsung Galaxy S20 FE', canonicalVariant: null },
  { aliasBase: 'Samsung S21', aliasVariant: null, canonicalBase: 'Samsung Galaxy S21', canonicalVariant: null },
  { aliasBase: 'Samsung S22', aliasVariant: null, canonicalBase: 'Samsung Galaxy S22', canonicalVariant: null },
  { aliasBase: 'Samsung S23', aliasVariant: null, canonicalBase: 'Samsung Galaxy S23', canonicalVariant: null },
  { aliasBase: 'Samsung S24', aliasVariant: null, canonicalBase: 'Samsung Galaxy S24', canonicalVariant: null },
  { aliasBase: 'Samsung S25', aliasVariant: null, canonicalBase: 'Samsung Galaxy S25', canonicalVariant: null },
  {
    aliasBase: 'Samsung S26 Ultra',
    aliasVariant: null,
    canonicalBase: 'Samsung Galaxy S26',
    canonicalVariant: 'Ultra',
  },
  // 5G-only models: bare "5G" tier is noise (no 4G sibling exists in this catalog)
  { aliasBase: 'Samsung Galaxy A36', aliasVariant: '5G', canonicalBase: 'Samsung Galaxy A36', canonicalVariant: null },
  { aliasBase: 'Samsung Galaxy A53', aliasVariant: '5G', canonicalBase: 'Samsung Galaxy A53', canonicalVariant: null },
  { aliasBase: 'Samsung Galaxy A54', aliasVariant: '5G', canonicalBase: 'Samsung Galaxy A54', canonicalVariant: null },
  { aliasBase: 'Samsung Galaxy A55', aliasVariant: '5G', canonicalBase: 'Samsung Galaxy A55', canonicalVariant: null },
  { aliasBase: 'Samsung Galaxy A56', aliasVariant: '5G', canonicalBase: 'Samsung Galaxy A56', canonicalVariant: null },
  { aliasBase: 'Samsung Galaxy A57', aliasVariant: '5G', canonicalBase: 'Samsung Galaxy A57', canonicalVariant: null },
  { aliasBase: 'Samsung Galaxy S21', aliasVariant: '5G', canonicalBase: 'Samsung Galaxy S21', canonicalVariant: null },
  { aliasBase: 'Samsung Galaxy S22', aliasVariant: '5G', canonicalBase: 'Samsung Galaxy S22', canonicalVariant: null },
  { aliasBase: 'Samsung Galaxy S25', aliasVariant: '5G', canonicalBase: 'Samsung Galaxy S25', canonicalVariant: null },
  {
    aliasBase: 'Samsung Galaxy A17 5G',
    aliasVariant: null,
    canonicalBase: 'Samsung Galaxy A17',
    canonicalVariant: '5G',
  },
  {
    aliasBase: 'Samsung Galaxy A54 5G',
    aliasVariant: null,
    canonicalBase: 'Samsung Galaxy A54',
    canonicalVariant: '5G',
  },
  {
    aliasBase: 'Samsung Galaxy A57 5G',
    aliasVariant: null,
    canonicalBase: 'Samsung Galaxy A57',
    canonicalVariant: '5G',
  },
  {
    aliasBase: 'Samsung Galaxy Tab 11',
    aliasVariant: null,
    canonicalBase: 'Samsung Galaxy Tab A11',
    canonicalVariant: null,
  },

  // ---- Xiaomi / Redmi / Poco ----
  { aliasBase: 'Xiaomi Redmi Note 12', aliasVariant: null, canonicalBase: 'Redmi Note 12', canonicalVariant: null },
  { aliasBase: 'Xiaomi Redmi 15', aliasVariant: '5G', canonicalBase: 'Redmi 15', canonicalVariant: '5G' },
  { aliasBase: 'Xiaomi Redmi 15C', aliasVariant: null, canonicalBase: 'Redmi 15C', canonicalVariant: null },
  { aliasBase: 'Xiaomi Redmi A5', aliasVariant: null, canonicalBase: 'Redmi A5', canonicalVariant: null },
  { aliasBase: 'Xiaomi Redmi Pad 2', aliasVariant: null, canonicalBase: 'Redmi Pad 2', canonicalVariant: null },
  { aliasBase: 'Xiaomi Redmi Note 10', aliasVariant: 'Pro', canonicalBase: 'Redmi Note 10', canonicalVariant: 'Pro' },
  {
    aliasBase: 'Xiaomi Redmi Note 14',
    aliasVariant: 'Pro 5G',
    canonicalBase: 'Redmi Note 14',
    canonicalVariant: 'Pro 5G',
  },
  { aliasBase: 'Xiaomi Poco X6', aliasVariant: 'Pro 5G', canonicalBase: 'Poco X6', canonicalVariant: 'Pro' },
  { aliasBase: 'Xiaomi Redmi Pad', aliasVariant: 'Pro', canonicalBase: 'Redmi Pad', canonicalVariant: 'Pro' },
  { aliasBase: 'Redmi Pad Pro', aliasVariant: null, canonicalBase: 'Redmi Pad', canonicalVariant: 'Pro' },
  { aliasBase: 'Redmi Note 13', aliasVariant: 'Pro+ 5G', canonicalBase: 'Redmi Note 13', canonicalVariant: 'Pro Plus' },
  { aliasBase: 'Redmi Note 14', aliasVariant: 'Pro+', canonicalBase: 'Redmi Note 14', canonicalVariant: 'Pro Plus' },
  { aliasBase: 'Redmi Note 13 Pro', aliasVariant: null, canonicalBase: 'Redmi Note 13', canonicalVariant: 'Pro' },
  { aliasBase: 'Poco X3 Pro', aliasVariant: null, canonicalBase: 'Poco X3', canonicalVariant: 'Pro' },
  { aliasBase: 'Poco X4', aliasVariant: 'Pro 5G', canonicalBase: 'Poco X4', canonicalVariant: 'Pro' },

  // ---- Oppo ----
  { aliasBase: 'Oppo Reno 12F', aliasVariant: null, canonicalBase: 'Oppo Reno 12', canonicalVariant: 'F' },
  { aliasBase: 'Oppo Reno12 F', aliasVariant: null, canonicalBase: 'Oppo Reno 12', canonicalVariant: 'F' },
  { aliasBase: 'Oppo Reno 12F', aliasVariant: '5G', canonicalBase: 'Oppo Reno 12', canonicalVariant: 'F' },
  { aliasBase: 'Oppo Reno8 T', aliasVariant: '5G', canonicalBase: 'Oppo Reno 8T', canonicalVariant: '5G' },
  { aliasBase: 'Oppo Reno8T', aliasVariant: '5G', canonicalBase: 'Oppo Reno 8T', canonicalVariant: '5G' },
  { aliasBase: 'OPPO Reno11', aliasVariant: '5G', canonicalBase: 'Oppo Reno 11', canonicalVariant: null },
  { aliasBase: 'Oppo Reno 11', aliasVariant: '5G', canonicalBase: 'Oppo Reno 11', canonicalVariant: null },
  { aliasBase: 'Oppo Reno 13F', aliasVariant: '5G', canonicalBase: 'Oppo Reno 13', canonicalVariant: 'F' },
  { aliasBase: 'Oppo Reno 13', aliasVariant: 'F 5G', canonicalBase: 'Oppo Reno 13', canonicalVariant: 'F' },
  { aliasBase: 'Oppo Reno 14F', aliasVariant: '5G', canonicalBase: 'Oppo Reno 14', canonicalVariant: 'F' },
  { aliasBase: 'Oppo Reno 14F 5G', aliasVariant: null, canonicalBase: 'Oppo Reno 14', canonicalVariant: 'F' },
  { aliasBase: 'Oppo Reno 14', aliasVariant: 'F 5G', canonicalBase: 'Oppo Reno 14', canonicalVariant: 'F' },
  { aliasBase: 'Oppo Reno 2f', aliasVariant: null, canonicalBase: 'Oppo Reno 2', canonicalVariant: 'F' },
  { aliasBase: 'OPPO Reno2', aliasVariant: 'F', canonicalBase: 'Oppo Reno 2', canonicalVariant: 'F' },
  { aliasBase: 'Oppo Reno 7z', aliasVariant: null, canonicalBase: 'Oppo Reno 7', canonicalVariant: 'Z' },
  { aliasBase: 'Oppo A6', aliasVariant: 'Pro 5G', canonicalBase: 'OPPO A6', canonicalVariant: 'Pro' },

  // ---- Vivo / Realme / Honor / Infinix / Tecno ----
  { aliasBase: 'vivo V40 Lite', aliasVariant: null, canonicalBase: 'Vivo V40', canonicalVariant: 'Lite' },
  { aliasBase: 'Vivo V40 Lite', aliasVariant: '5G', canonicalBase: 'Vivo V40', canonicalVariant: 'Lite 5G' },
  { aliasBase: 'Vivo V50 Lite', aliasVariant: null, canonicalBase: 'Vivo V50', canonicalVariant: 'Lite' },
  { aliasBase: 'Vivo V60 Lite', aliasVariant: null, canonicalBase: 'Vivo V60', canonicalVariant: 'Lite' },
  { aliasBase: 'Vivo V60 Lite', aliasVariant: '5G', canonicalBase: 'Vivo V60', canonicalVariant: 'Lite' },
  { aliasBase: 'Vivo V60', aliasVariant: '5G', canonicalBase: 'Vivo V60', canonicalVariant: null },
  { aliasBase: 'Vivo V50', aliasVariant: '5G', canonicalBase: 'Vivo V50', canonicalVariant: null },
  { aliasBase: 'Vivo V70', aliasVariant: '5G', canonicalBase: 'Vivo V70', canonicalVariant: null },
  { aliasBase: 'Vivo V70', aliasVariant: '5G Zeiss', canonicalBase: 'Vivo V70', canonicalVariant: null },
  { aliasBase: 'Realme GT7t', aliasVariant: null, canonicalBase: 'Realme GT 7T', canonicalVariant: null },
  { aliasBase: 'Realme GT 7T', aliasVariant: '5G', canonicalBase: 'Realme GT 7T', canonicalVariant: null },
  { aliasBase: 'Realme GT 7T 5G', aliasVariant: null, canonicalBase: 'Realme GT 7T', canonicalVariant: null },
  { aliasBase: 'Honor 600 5G', aliasVariant: null, canonicalBase: 'Honor 600', canonicalVariant: null },
  { aliasBase: 'Honor 600', aliasVariant: '5G', canonicalBase: 'Honor 600', canonicalVariant: null },
  { aliasBase: 'Honor X9c', aliasVariant: '5G', canonicalBase: 'Honor X9c', canonicalVariant: null },
  { aliasBase: 'Honor X9d', aliasVariant: '5G', canonicalBase: 'Honor X9d', canonicalVariant: null },
  { aliasBase: 'Honor X9B', aliasVariant: '5G', canonicalBase: 'Honor X9b', canonicalVariant: null },
  { aliasBase: 'Honor X5c', aliasVariant: 'Plus', canonicalBase: 'Honor X5C Plus', canonicalVariant: null },
  { aliasBase: 'Infinix Note Edge', aliasVariant: null, canonicalBase: 'Infinix Note', canonicalVariant: 'Edge' },
  { aliasBase: 'Infinix Note Edge', aliasVariant: '5G', canonicalBase: 'Infinix Note', canonicalVariant: 'Edge' },
  { aliasBase: 'Infinix Hot 60', aliasVariant: 'Pro+', canonicalBase: 'Infinix Hot 60', canonicalVariant: 'Pro Plus' },
  { aliasBase: 'Hot 60', aliasVariant: 'Pro+', canonicalBase: 'Infinix Hot 60', canonicalVariant: 'Pro Plus' },
  { aliasBase: 'Infinix Hot 50', aliasVariant: 'Pro+', canonicalBase: 'Infinix Hot 50', canonicalVariant: 'Pro Plus' },
  { aliasBase: 'Infinix GT 30', aliasVariant: 'Pro 5G', canonicalBase: 'Infinix GT 30', canonicalVariant: 'Pro' },
  { aliasBase: 'Infinix GT 30 5G', aliasVariant: 'Pro', canonicalBase: 'Infinix GT 30', canonicalVariant: 'Pro' },
  {
    aliasBase: 'Infinix GT 30',
    aliasVariant: 'Pro 5G Gaming Master Edition',
    canonicalBase: 'Infinix GT 30',
    canonicalVariant: 'Pro Master Edition',
  },
  { aliasBase: 'Smart 10', aliasVariant: null, canonicalBase: 'Infinix Smart 10', canonicalVariant: null },
  { aliasBase: 'Tecno Spark Go', aliasVariant: '1', canonicalBase: 'Tecno Spark Go 1', canonicalVariant: null },
  { aliasBase: 'Tecno Spark Go', aliasVariant: '2024', canonicalBase: 'TECNO Spark Go 2024', canonicalVariant: null },
  { aliasBase: 'Tecno Spark', aliasVariant: 'Slim', canonicalBase: 'TECNO SPARK SLIM', canonicalVariant: null },
  { aliasBase: 'Tecno MegaPad', aliasVariant: 'SE', canonicalBase: 'Tecno MegaPad SE', canonicalVariant: null },
  { aliasBase: 'Tecno Camon', aliasVariant: '40 Pro 5G', canonicalBase: 'Tecno Camon 40', canonicalVariant: 'Pro' },
  { aliasBase: 'Tecno Camon 40', aliasVariant: 'Pro 5G', canonicalBase: 'Tecno Camon 40', canonicalVariant: 'Pro' },
  { aliasBase: 'Tecno Camon 40', aliasVariant: '4.5G', canonicalBase: 'Tecno Camon 40', canonicalVariant: null },
  { aliasBase: 'Tecno Pova 7', aliasVariant: 'Ultra 5G', canonicalBase: 'Tecno Pova 7', canonicalVariant: 'Ultra' },

  // ---- Huawei ----
  {
    aliasBase: 'Huawei MateBook D 16',
    aliasVariant: null,
    canonicalBase: 'Huawei MateBook D16',
    canonicalVariant: null,
  },
  { aliasBase: 'Huawei MatePad', aliasVariant: '11.5', canonicalBase: 'Huawei Matepad 11.5', canonicalVariant: null },
  {
    aliasBase: 'Huawei MatePad 11.5',
    aliasVariant: 'PaperMatte',
    canonicalBase: 'Huawei Matepad 11.5',
    canonicalVariant: 'PaperMatte Edition',
  },
  {
    aliasBase: 'Huawei MatePad 11.5 S',
    aliasVariant: null,
    canonicalBase: 'Huawei MatePad 11.5',
    canonicalVariant: 'S',
  },
  { aliasBase: 'Pura 80', aliasVariant: null, canonicalBase: 'Huawei Pura 80', canonicalVariant: null },

  // ---- Gaming ----
  { aliasBase: 'PS4 Slim', aliasVariant: null, canonicalBase: 'PlayStation 4', canonicalVariant: 'Slim' },
  { aliasBase: 'PS4', aliasVariant: 'Slim', canonicalBase: 'PlayStation 4', canonicalVariant: 'Slim' },
  { aliasBase: 'PS4', aliasVariant: 'Phat', canonicalBase: 'PlayStation 4', canonicalVariant: 'Phat' },
  { aliasBase: 'PS5', aliasVariant: 'Slim', canonicalBase: 'PlayStation 5', canonicalVariant: 'Slim' },
  { aliasBase: 'Sony PlayStation 4', aliasVariant: 'Pro', canonicalBase: 'PlayStation 4', canonicalVariant: 'Pro' },
  { aliasBase: 'Nintendo Switch 2', aliasVariant: null, canonicalBase: 'Nintendo Switch', canonicalVariant: '2' },
  { aliasBase: 'Switch 2', aliasVariant: null, canonicalBase: 'Nintendo Switch', canonicalVariant: '2' },
  { aliasBase: 'Nintendo Switch Lite', aliasVariant: null, canonicalBase: 'Nintendo Switch', canonicalVariant: 'Lite' },
  { aliasBase: 'Nintendo Switch', aliasVariant: 'Standard', canonicalBase: 'Nintendo Switch', canonicalVariant: null },
  { aliasBase: 'Mario Kart 8 Deluxe', aliasVariant: null, canonicalBase: 'Mario Kart 8', canonicalVariant: 'Deluxe' },
  { aliasBase: 'ROG Ally Z1', aliasVariant: 'Extreme', canonicalBase: 'ROG Ally', canonicalVariant: 'Z1 Extreme' },
  { aliasBase: 'Asus ROG Ally', aliasVariant: 'Z1 Extreme', canonicalBase: 'ROG Ally', canonicalVariant: 'Z1 Extreme' },
  {
    aliasBase: 'ASUS ROG Ally',
    aliasVariant: 'Ryzen Z1 Extreme',
    canonicalBase: 'ROG Ally',
    canonicalVariant: 'Z1 Extreme',
  },

  // ---- PC / components ----
  { aliasBase: 'GTX 750TI', aliasVariant: null, canonicalBase: 'GTX 750 Ti', canonicalVariant: null },
  { aliasBase: 'RTX 5060ti', aliasVariant: null, canonicalBase: 'RTX 5060 Ti', canonicalVariant: null },
  { aliasBase: 'MSI GTX 1650', aliasVariant: null, canonicalBase: 'GTX 1650', canonicalVariant: null },
  { aliasBase: 'MSI GTX 1050 Ti', aliasVariant: null, canonicalBase: 'GTX 1050 Ti', canonicalVariant: null },
  { aliasBase: 'DDR4 SODIMM RAM', aliasVariant: null, canonicalBase: 'DDR4 SO-DIMM RAM', canonicalVariant: null },
  { aliasBase: 'Kingston RAM', aliasVariant: 'DDR4 SODIMM', canonicalBase: 'DDR4 SO-DIMM RAM', canonicalVariant: null },
  {
    aliasBase: 'Kingston DDR4 SODIMM RAM',
    aliasVariant: null,
    canonicalBase: 'DDR4 SO-DIMM RAM',
    canonicalVariant: null,
  },
  {
    aliasBase: 'Kingston HyperX Fury RAM',
    aliasVariant: null,
    canonicalBase: 'HyperX Fury RAM',
    canonicalVariant: null,
  },
  { aliasBase: 'Acer Nitro V15', aliasVariant: null, canonicalBase: 'Acer Nitro V 15', canonicalVariant: null },
  {
    aliasBase: 'Lenovo IdeaPad',
    aliasVariant: 'Slim 3',
    canonicalBase: 'Lenovo IdeaPad Slim 3',
    canonicalVariant: null,
  },
  {
    aliasBase: 'Predator Helios Neo 16',
    aliasVariant: null,
    canonicalBase: 'Acer Predator Helios Neo 16',
    canonicalVariant: null,
  },
  {
    aliasBase: 'Logitech G Pro X',
    aliasVariant: 'Superlight',
    canonicalBase: 'Logitech G Pro X Superlight',
    canonicalVariant: null,
  },

  // ---- Cameras / drones ----
  { aliasBase: 'Insta360 Ace', aliasVariant: 'Pro 2', canonicalBase: 'Insta360 Ace Pro 2', canonicalVariant: null },
  { aliasBase: 'Insta360 Ace', aliasVariant: 'Pro', canonicalBase: 'Insta360 Ace Pro', canonicalVariant: null },
  {
    aliasBase: 'Insta360 X5',
    aliasVariant: 'essential',
    canonicalBase: 'Insta360 X5',
    canonicalVariant: 'Essential Bundle',
  },
  {
    aliasBase: 'Insta360 X5',
    aliasVariant: 'Essentials Bundle',
    canonicalBase: 'Insta360 X5',
    canonicalVariant: 'Essential Bundle',
  },
  { aliasBase: 'Sony ZV-E10', aliasVariant: 'II', canonicalBase: 'Sony ZV-E10', canonicalVariant: 'Mark II' },
  { aliasBase: 'GoPro Hero 13', aliasVariant: null, canonicalBase: 'GoPro HERO13', canonicalVariant: null },
  {
    aliasBase: 'Fujifilm Instax',
    aliasVariant: 'Mini Evo',
    canonicalBase: 'Fujifilm Instax Mini Evo',
    canonicalVariant: null,
  },
  {
    aliasBase: 'Instax Mini Evo',
    aliasVariant: null,
    canonicalBase: 'Fujifilm Instax Mini Evo',
    canonicalVariant: null,
  },
  { aliasBase: 'DJI Osmo', aliasVariant: '360', canonicalBase: 'DJI Osmo 360', canonicalVariant: null },
  { aliasBase: 'LITO X1', aliasVariant: null, canonicalBase: 'DJI Lito X1', canonicalVariant: null },
  { aliasBase: 'Lumix GM1', aliasVariant: null, canonicalBase: 'Panasonic Lumix GM1', canonicalVariant: null },
  { aliasBase: 'DJI Neo 2', aliasVariant: 'Standard', canonicalBase: 'DJI Neo 2', canonicalVariant: null },

  // ---- Motorcycles ----
  { aliasBase: 'Yamaha Mio i 125s', aliasVariant: null, canonicalBase: 'Yamaha Mio i 125', canonicalVariant: 'S' },
  { aliasBase: 'Mio i 125', aliasVariant: 'S', canonicalBase: 'Yamaha Mio i 125', canonicalVariant: 'S' },
  { aliasBase: 'Mio i 125', aliasVariant: null, canonicalBase: 'Yamaha Mio i 125', canonicalVariant: null },
  { aliasBase: 'Yamaha Mio', aliasVariant: 'i125', canonicalBase: 'Yamaha Mio i 125', canonicalVariant: null },
  { aliasBase: 'Mio Soul i 125', aliasVariant: null, canonicalBase: 'Yamaha Mio Soul i 125', canonicalVariant: null },
  { aliasBase: 'Mio Soulty', aliasVariant: null, canonicalBase: 'Yamaha Mio Soulty', canonicalVariant: null },
  { aliasBase: 'Yamaha Mio', aliasVariant: 'Sporty', canonicalBase: 'Yamaha Mio Sporty', canonicalVariant: null },
  { aliasBase: 'Mio Sporty', aliasVariant: null, canonicalBase: 'Yamaha Mio Sporty', canonicalVariant: null },
  { aliasBase: 'Yamaha Aerox V2', aliasVariant: null, canonicalBase: 'Yamaha Aerox 155', canonicalVariant: 'V2' },
  { aliasBase: 'Yamaha Aerox', aliasVariant: 'V2', canonicalBase: 'Yamaha Aerox 155', canonicalVariant: 'V2' },
  { aliasBase: 'Yamaha Aerox', aliasVariant: null, canonicalBase: 'Yamaha Aerox 155', canonicalVariant: null },
  { aliasBase: 'NMAX', aliasVariant: null, canonicalBase: 'Yamaha NMAX', canonicalVariant: null },
  { aliasBase: 'Nmax', aliasVariant: 'v2', canonicalBase: 'Yamaha NMAX', canonicalVariant: 'V2' },
  { aliasBase: 'Sniper 150', aliasVariant: null, canonicalBase: 'Yamaha Sniper 150', canonicalVariant: null },
  { aliasBase: 'Sniper 155', aliasVariant: null, canonicalBase: 'Yamaha Sniper 155', canonicalVariant: null },
  { aliasBase: 'PCX', aliasVariant: null, canonicalBase: 'Honda PCX', canonicalVariant: null },
  { aliasBase: 'RAIDER FI', aliasVariant: null, canonicalBase: 'Suzuki Raider FI', canonicalVariant: null },
  { aliasBase: 'Sigma250', aliasVariant: null, canonicalBase: 'Rusi Sigma 250', canonicalVariant: null },
  { aliasBase: 'Kawasaki Barako 1', aliasVariant: null, canonicalBase: 'Kawasaki Barako', canonicalVariant: '1' },
  { aliasBase: 'Honda ADV160', aliasVariant: null, canonicalBase: 'Honda ADV 160', canonicalVariant: null },
  { aliasBase: 'Honda Beat V2', aliasVariant: null, canonicalBase: 'Honda Beat', canonicalVariant: 'v2' },

  // ---- Air conditioners ----
  {
    aliasBase: 'LG Aircon',
    aliasVariant: 'Dual Inverter Window Type',
    canonicalBase: 'LG Air Conditioner',
    canonicalVariant: 'Dual Inverter Window Type',
  },
  {
    aliasBase: 'LG Dual Inverter Air Conditioner',
    aliasVariant: 'Window Type',
    canonicalBase: 'LG Air Conditioner',
    canonicalVariant: 'Dual Inverter Window Type',
  },
  {
    aliasBase: 'LG Dual Inverter Aircon',
    aliasVariant: 'Window Type',
    canonicalBase: 'LG Air Conditioner',
    canonicalVariant: 'Dual Inverter Window Type',
  },
  {
    aliasBase: 'LG Window Type Aircon',
    aliasVariant: 'Dual Inverter',
    canonicalBase: 'LG Air Conditioner',
    canonicalVariant: 'Dual Inverter Window Type',
  },
  {
    aliasBase: 'LG Window Type Dual Inverter Air Conditioner',
    aliasVariant: null,
    canonicalBase: 'LG Air Conditioner',
    canonicalVariant: 'Dual Inverter Window Type',
  },
  {
    aliasBase: 'LG Dual Inverter Window Type Air Conditioner',
    aliasVariant: 'Dual Inverter',
    canonicalBase: 'LG Air Conditioner',
    canonicalVariant: 'Dual Inverter Window Type',
  },
  { aliasBase: 'LG Aircon', aliasVariant: null, canonicalBase: 'LG Air Conditioner', canonicalVariant: null },
  { aliasBase: 'Carrier Aircon', aliasVariant: null, canonicalBase: 'Carrier Air Conditioner', canonicalVariant: null },
  { aliasBase: 'Condura Aircon', aliasVariant: null, canonicalBase: 'Condura Air Conditioner', canonicalVariant: null },
  { aliasBase: 'Midea Aircon', aliasVariant: null, canonicalBase: 'Midea Air Conditioner', canonicalVariant: null },
  {
    aliasBase: 'Panasonic Aircon',
    aliasVariant: null,
    canonicalBase: 'Panasonic Air Conditioner',
    canonicalVariant: null,
  },
  { aliasBase: 'TCL Aircon', aliasVariant: null, canonicalBase: 'TCL Air Conditioner', canonicalVariant: null },
  { aliasBase: 'Astron Aircon', aliasVariant: null, canonicalBase: 'Astron Air Conditioner', canonicalVariant: null },
  { aliasBase: 'Everest Aircon', aliasVariant: null, canonicalBase: 'Everest Air Conditioner', canonicalVariant: null },
  { aliasBase: 'Aircon', aliasVariant: null, canonicalBase: 'Air Conditioner', canonicalVariant: null },
  { aliasBase: 'Aircon', aliasVariant: 'Inverter', canonicalBase: 'Air Conditioner', canonicalVariant: 'Inverter' },
  {
    aliasBase: 'Portable Aircon',
    aliasVariant: null,
    canonicalBase: 'Portable Air Conditioner',
    canonicalVariant: null,
  },
  {
    aliasBase: 'Window Type Aircon',
    aliasVariant: null,
    canonicalBase: 'Window Air Conditioner',
    canonicalVariant: null,
  },
  {
    aliasBase: 'Window Type Air Conditioner',
    aliasVariant: null,
    canonicalBase: 'Window Air Conditioner',
    canonicalVariant: null,
  },

  // ---- Redundant tier / misc spelling ----
  {
    aliasBase: 'Tomler Mini Refrigerator',
    aliasVariant: 'Mini',
    canonicalBase: 'Tomler Mini Refrigerator',
    canonicalVariant: null,
  },
  { aliasBase: 'Devant Smart TV', aliasVariant: 'Smart', canonicalBase: 'Devant Smart TV', canonicalVariant: null },
  { aliasBase: 'TCL Smart TV', aliasVariant: 'Smart TV', canonicalBase: 'TCL Smart TV', canonicalVariant: null },
  {
    aliasBase: 'Panasonic Inverter Refrigerator',
    aliasVariant: 'Inverter',
    canonicalBase: 'Panasonic Inverter Refrigerator',
    canonicalVariant: null,
  },
  { aliasBase: 'Haier Google TV', aliasVariant: 'Smart TV', canonicalBase: 'Haier Google TV', canonicalVariant: null },
  {
    aliasBase: 'SHOKZ OpenMove',
    aliasVariant: 'Bone Conduction Headphones',
    canonicalBase: 'Shokz OpenMove',
    canonicalVariant: null,
  },
  {
    aliasBase: 'SHOKZ OpenMove Bone Conduction Headphones',
    aliasVariant: null,
    canonicalBase: 'Shokz OpenMove',
    canonicalVariant: null,
  },
  {
    aliasBase: 'Refrigerator',
    aliasVariant: 'Non-inverter',
    canonicalBase: 'Refrigerator',
    canonicalVariant: 'Non Inverter',
  },
  {
    aliasBase: 'Juki Sewing Machine',
    aliasVariant: 'Highspeed',
    canonicalBase: 'JUKI Sewing Machine',
    canonicalVariant: 'High Speed',
  },
  {
    aliasBase: 'Whirlpool Washing Machine',
    aliasVariant: 'Automatic',
    canonicalBase: 'Whirlpool Washing Machine',
    canonicalVariant: null,
  },
  {
    aliasBase: 'Hanabishi Washing Machine',
    aliasVariant: 'Fully Automatic',
    canonicalBase: 'Hanabishi Washing Machine',
    canonicalVariant: null,
  },
  { aliasBase: 'Bedframe', aliasVariant: null, canonicalBase: 'Bed Frame', canonicalVariant: null },
  { aliasBase: 'Sofabed', aliasVariant: null, canonicalBase: 'Sofa Bed', canonicalVariant: null },
  { aliasBase: 'L Shape Sofa', aliasVariant: null, canonicalBase: 'L-Shape Sofa', canonicalVariant: null },
  { aliasBase: 'Sofa', aliasVariant: '2 Seater', canonicalBase: 'Sofa', canonicalVariant: '2-Seater' },
  { aliasBase: 'Balik Bayan Box', aliasVariant: null, canonicalBase: 'Balikbayan Box', canonicalVariant: null },
  { aliasBase: 'Balikbayan Boxes', aliasVariant: null, canonicalBase: 'Balikbayan Box', canonicalVariant: null },
  { aliasBase: 'Bubblewrap', aliasVariant: null, canonicalBase: 'Bubble Wrap', canonicalVariant: null },
  { aliasBase: 'Ebike', aliasVariant: null, canonicalBase: 'E-Bike', canonicalVariant: null },
  { aliasBase: 'Piso Net', aliasVariant: null, canonicalBase: 'Pisonet', canonicalVariant: null },
  { aliasBase: 'Side Car', aliasVariant: null, canonicalBase: 'Sidecar', canonicalVariant: null },
  { aliasBase: 'Rain Coat', aliasVariant: null, canonicalBase: 'Raincoat', canonicalVariant: null },
  { aliasBase: 'Wheel Set', aliasVariant: null, canonicalBase: 'Wheelset', canonicalVariant: null },
  { aliasBase: 'Rimset', aliasVariant: null, canonicalBase: 'Rim Set', canonicalVariant: null },
  { aliasBase: 'Croptop', aliasVariant: null, canonicalBase: 'Crop Top', canonicalVariant: null },
  { aliasBase: 'Crop Tops', aliasVariant: null, canonicalBase: 'Crop Top', canonicalVariant: null },
  { aliasBase: 'Full Body Mirror', aliasVariant: null, canonicalBase: 'Full-Body Mirror', canonicalVariant: null },
  { aliasBase: 'Press-on Nails', aliasVariant: null, canonicalBase: 'Press On Nails', canonicalVariant: null },
  { aliasBase: 'Superkalan', aliasVariant: null, canonicalBase: 'Super Kalan', canonicalVariant: null },
  { aliasBase: 'Cross Body Bag', aliasVariant: null, canonicalBase: 'Crossbody Bag', canonicalVariant: null },
  {
    aliasBase: 'Havaianas Flip-Flops',
    aliasVariant: null,
    canonicalBase: 'Havaianas Flip Flops',
    canonicalVariant: null,
  },
  { aliasBase: 'Skechers Slip-ins', aliasVariant: null, canonicalBase: 'Skechers Slipins', canonicalVariant: null },
  { aliasBase: 'DITO WiFi Router', aliasVariant: null, canonicalBase: 'DITO Wi-Fi Router', canonicalVariant: null },
  {
    aliasBase: 'CPU, Motherboard &amp; RAM Bundle',
    aliasVariant: null,
    canonicalBase: 'CPU Motherboard RAM Bundle',
    canonicalVariant: null,
  },
  {
    aliasBase: '1-Bedroom Apartment',
    aliasVariant: null,
    canonicalBase: '1 Bedroom Apartment',
    canonicalVariant: null,
  },
  {
    aliasBase: '1 Bedroom Condo Unit',
    aliasVariant: null,
    canonicalBase: '1-Bedroom Condo Unit',
    canonicalVariant: null,
  },
  { aliasBase: 'Cabinet Drawer', aliasVariant: null, canonicalBase: 'Cabinet &amp; Drawer', canonicalVariant: null },
  { aliasBase: 'Pull Out Bed', aliasVariant: null, canonicalBase: 'Pull-Out Bed', canonicalVariant: null },
  { aliasBase: 'Motorstar 125', aliasVariant: null, canonicalBase: 'Motor Star 125', canonicalVariant: null },
  { aliasBase: 'NS 1250a', aliasVariant: null, canonicalBase: 'NS. 1250a', canonicalVariant: null },
  { aliasBase: 'Nvision Monitor', aliasVariant: null, canonicalBase: 'N-Vision Monitor', canonicalVariant: null },
  { aliasBase: 'XP Pen Deco 01', aliasVariant: null, canonicalBase: 'XP-Pen Deco 01', canonicalVariant: null },
  { aliasBase: 'Kobo Clara BW', aliasVariant: null, canonicalBase: 'Kobo Clara', canonicalVariant: 'BW' },
  {
    aliasBase: 'Fender Standard Stratocaster HSS',
    aliasVariant: null,
    canonicalBase: 'Fender Standard Stratocaster',
    canonicalVariant: 'HSS',
  },
  {
    aliasBase: 'Shimano Deore M6250 Di2',
    aliasVariant: null,
    canonicalBase: 'Shimano Deore M6250',
    canonicalVariant: 'Di2',
  },
  {
    aliasBase: 'Wika Baofire Evolution',
    aliasVariant: '2',
    canonicalBase: 'Wika Bao Fire',
    canonicalVariant: 'Evolution 2',
  },
  { aliasBase: 'Moving Head Lights', aliasVariant: null, canonicalBase: 'Moving Head Light', canonicalVariant: null },
  { aliasBase: 'Dyson Airwrap', aliasVariant: 'ID', canonicalBase: 'Dyson Airwrap', canonicalVariant: 'i.d.' },
  {
    aliasBase: 'Dyson Airwrap',
    aliasVariant: 'i.d.™ Multi-Styler and Dryer',
    canonicalBase: 'Dyson Airwrap',
    canonicalVariant: 'i.d.',
  },

  // ---- Shoes ----
  { aliasBase: 'Nike Dunk Low', aliasVariant: null, canonicalBase: 'Nike Dunk', canonicalVariant: 'Low' },
  { aliasBase: 'Nike Dunks', aliasVariant: null, canonicalBase: 'Nike Dunk', canonicalVariant: null },
  { aliasBase: 'Air Force 1', aliasVariant: null, canonicalBase: 'Nike Air Force 1', canonicalVariant: null },
  { aliasBase: 'Nike Air Jordan 1', aliasVariant: 'Low', canonicalBase: 'Air Jordan 1', canonicalVariant: 'Low' },
  {
    aliasBase: 'Nike Metcon 4',
    aliasVariant: 'HWPO Matt Fraser',
    canonicalBase: 'Nike Metcon 4',
    canonicalVariant: 'Matt Fraser HWPO',
  },
]
