import type { Logger } from '../../platform/logger'
import type { DbClient } from '../../platform/storage'
import type { PriceExclusionReason } from './exclusion'
import { excludeFromPricing } from './exclusion'

// Applied by a manual script, NOT a continuously-running worker, deliberately
// - unlike the automatic Groq-derived half of eligibility gating
// (applyEligibilityFromEnrichment, run by the enrich-products worker's own
// loop, since it needs to react to new enrichment rows as they're produced),
// this list only ever needs to re-run when a human edits it. Run manually
// (`pnpm run flag-price-ineligible`) right after adding an entry below -
// idempotent, matches on base_model text, safe to re-run anytime regardless.
//
// Manually curated (2026-08-23) from a real scan of distinct products.base_model
// values — "new-retail price" is a meaningless concept for these, so both
// price-lookup.ts would otherwise waste a paid/quota-limited call on
// them. Re-run whenever a new batch of
// extraction turns up more junk categories — idempotent, matches on
// base_model text.
const PRICE_INELIGIBLE_CATEGORIES: Partial<Record<PriceExclusionReason, string[]>> = {
  real_estate: [
    'Apartment',
    'Condo',
    'Condo Unit',
    'Condominium',
    'Condominium Unit',
    'House',
    'House & Lot',
    'House and Lot',
    'House and Rights',
    'Land Lot',
    'Lot',
    'Property',
    // Specific PH condo/house project names — same wrong domain as the
    // generic entries above, just not caught by exact-string matching until
    // a full pending-candidate scan surfaced them (2026-08-23).
    '1 Bedroom Condo Unit',
    'Ancestral House',
    'Arya Residences Penthouse',
    'Commercial House',
    'Commercial Space',
    'Fort Victoria Condo Unit',
    'GA Tower Condo Unit',
    'Grass Residences Condo Unit',
    'R Square Residences Condo Unit',
    'SMDC Breeze Residences Condo Unit',
    'Townhouse',
    'Warehouse and Lot',
    // Found live 2026-08-29 via a broader base_model scan of all remaining
    // unpriced candidates (not just the pending-candidate pool) - same real
    // estate problem, wider net (word-boundary matched on condo/tower/
    // residences/lot/apartment/etc, manually reviewed to drop false
    // positives like "Goat House"/"Toy Lot" where the matched word wasn't
    // actually real estate; those went to too_generic below instead).
    '1-Bedroom Apartment',
    '1-Bedroom Condo Unit',
    '1BR Unit',
    '2-Bedroom Apartment',
    '2-Bedroom Condo',
    '8 Adriatico Condo Unit',
    'Amaia Series Vermosa House',
    'Amaia Skies Shaw Tower 2',
    'Apartment Appliances',
    'Apartment Building & Lot',
    'Apartment/Condo',
    'Arya Residences',
    'Avida 34th 2BR Unit',
    'Avida Cityflex Tower 1 Studio Unit',
    'Bedspace',
    'Bel Air Village House and Lot',
    'Blue Residences Katipunan',
    'Building',
    'Fairway Lot',
    'Forbeswood Heights Parking Slot',
    'Fort Victoria Condominium',
    'Fortunata GardenCity 3-Storey House',
    'GA Tower 2',
    'Glam Residences Condo Unit',
    'Harbour Park Residences Condo Unit',
    'House with Private Pool',
    'Infina Tower Condominium',
    'Jazz Residences 1 BR Unit',
    'Madrid Tower 3 Condominium',
    'Maple Tower Condominium',
    'Maripaz Subdivision Lot',
    'Maven Condo Unit',
    'Memorial Lawn Lot',
    'Monte Verde Executive Village Lot',
    'Oak Harbor Residences',
    'Palm Beach West Condo',
    'Palm Beach West Condominium',
    'Park Triangle Residences',
    'Real Estate Lot',
    'Residences at The Galleon',
    'SM Light Residences Condominium Unit',
    'SMDC Trees Residences Condo Unit',
    'Shang Salcedo Place Condominium',
    'Shore Residences',
    'Southwynd Residences',
    'Studio Condo',
    'Studio Type Condo Unit',
    'Suntrust Shanata Condo',
    'The Oriental Place Studio Unit',
    'The Royalton Condo',
    'The Trion Towers 1BR Condo Unit',
    'Trees Residences',
    'Tropical Palm Residences',
    'Venice Luxury Residences',
    'Verve Residences Tower 1 Condominium',
    'Villa Olympia 6 House',
    'Vista Plumeria Condo',
    'Zadia Tower 3 Condo Unit',
    // Found live 2026-08-29 via detect-generic-products (src/modules/
    // pricing/generic-products.ts), reviewed before curating - 4 of the
    // detector's raw real_estate matches were dropped as false positives
    // ("Adjustable Learning Tower"/"Cougar Panzer Full Tower Casing" matched
    // on "tower", "KKV Area-X Patrick Star House Lego"/"Sylvanian Families
    // Waterside Red Roof House" matched on "house" - all real toys/PC parts,
    // not real estate), and 2 more ("Action Figure Lot"/"Action Figures
    // Lot", "lot" meaning a bundle here) moved to too_generic below instead.
    '2-Storey House',
    'Beach Property',
    'Bungalow Unit',
    'Condo Unit Grand Residences España 2',
    'Eagle Ridge Lot',
    'Greenwoods Lot',
    'Lawn Lot',
    'Lourdes Residences',
    'Palos Verdes Land Lot',
    'Resort',
    'Shore 2 Residences Unit',
    'Southplains Lot',
    'Studio Condo Unit',
    'Victoria De Morato Condo Unit',
    'Zuri Residences House & Lot',
  ],
  too_generic: [
    'Item',
    'Unidentified Product',
    'Unknown Product',
    'Bundle',
    'Electronics',
    'Electronics Bundle',
    'GPU',
    'Laptop',
    'Phone',
    'Watch',
    'Bag',
    'Shoes',
    'Clothing',
    'Jewelry',
    'Assorted Makeup',
    'Car',
    'Bicycle',
    'Bike',
    'Motorcycle',
    'Appliance',
    'Appliances',
    'Furniture and Appliances',
    'Speaker',
    // Bare component category, no brand/chipset/model — same problem as bare
    // 'GPU' above. Found live 2026-08-23: 'CPU' returned ₱11,095-38,090 (3.4x),
    // 'Intel Motherboard' ₱3,750-30,195 (8x), 'AM4 Motherboard' ₱3,395-20,495
    // (6x, spans budget A320 to high-end X570) — each spread spans an entire
    // product tier, not one product.
    'CPU',
    'Intel Motherboard',
    'AM4 Motherboard',
    'Household Appliances',
    'Household Furniture',
    'Power Supply Unit',
    // Found live 2026-08-23 via the dashboard's per-product discount badge -
    // 'Product' (literally the extraction fallback placeholder, real titles
    // were "Sale"/"Rush Sale"/"Decluter Sale") and bare 'Monitor' (no brand/
    // model) were bundling unrelated listings under one fake product, each
    // showing an 80-90% "discount" that was really just unrelated items
    // being compared to each other.
    'Product',
    'Monitor',
    // Found live 2026-08-26 via random-sampled candidate pool while testing
    // pricing sources — none of these are a single priceable product, same
    // reasoning as 'Item'/'GPU'/'CPU' above.
    'Other',
    'Miscellaneous',
    'Household Items',
    'Cellphone',
    'Smartphone',
    'System Unit',
    'Motherboard',
    'PC Parts Bundle',
    'Motherboard Bundle',
    'Furniture',
    'Clothes',
    'Dress',
    'Tops',
    'Preloved Clothes',
    'Office Clothes',
    'Formal Gown',
    'Cardigan',
    'Wheelset',
    // Real brand, no model/series number - same wide-spread problem as bare
    // 'Motherboard'/'CPU': real ThinkPad pricing spans PHP57,000-126,000+
    // depending on series (X/T/P/A/Yoga), confirmed live 2026-08-26.
    'Lenovo Thinkpad',
    // Found live 2026-08-29, same broader scan as real_estate above - bare
    // category nouns and brand+bare-category pairs with no model/series
    // number, same "spans an entire product tier" problem as 'Lenovo
    // Thinkpad'/'GPU' above (e.g. "Samsung Refrigerator" spans budget to
    // premium; "Aircon" alone spans window-type to multi-split inverter).
    'Adidas Clothing',
    'Adidas Sweater',
    'Air Conditioner',
    'Aircon',
    'American Home Refrigerator',
    'American Home Split Type Air Conditioner',
    'Apple Charger',
    'Asahi Electric Fan',
    'Assorted Items Lot',
    'Astron Air Conditioner',
    'Astron Aircon',
    'Astron Refrigerator',
    'Astron Washing Machine',
    'Astron Window Type Air Conditioner',
    'Baby Crib',
    'Backpack',
    'Batteries',
    'Bed',
    'Bed Frame',
    'Blazer',
    'Bookshelf',
    'Bunk Bed',
    'Butane Stove',
    'Carrier Aircon',
    'Carrier Window Type Air Conditioner',
    'Chair',
    'Chest Freezer',
    'Clamp',
    'Closet',
    'Coat',
    'Coffee Machine',
    'Coffee Maker',
    'Coinslot',
    'Condura Freezer',
    'Condura Microwave',
    'Condura Refrigerator',
    'Crib',
    'Dog House',
    'Drawer',
    'Dresses',
    'Electrolux Refrigerator',
    'Fujidenzo Aircon',
    'Fujidenzo Automatic Washing Machine',
    'Fujidenzo Gas Range',
    'Fujidenzo Mini Fridge',
    'Fujidenzo Refrigerator',
    'Fujidenzo Washing Machine',
    'Gas Range',
    'Glass Table',
    'Goat House',
    'Haier Air Conditioner',
    'Haier Washing Machine',
    'Hanabishi Air Conditioner',
    'Hanabishi Coffee Maker',
    'Hanabishi Electric Fan',
    'Hanabishi Microwave Oven',
    'Hanabishi Refrigerator',
    'Hanabishi Rice Cooker',
    'Hanabishi Washing Machine',
    'Headset',
    'Hisense Air Conditioner',
    'Hisense Aircon',
    'Hisense Refrigerator',
    'Humidifier',
    'Imarflex Coffee Maker',
    'Juicer',
    'Kolin Air Conditioner',
    'Koppel Aircon',
    'Koppel Window Type Air Conditioner',
    'LG Air Conditioner',
    'LG Aircon',
    'LG Microwave Oven',
    'LG Monitor',
    'LG Refrigerator',
    'LG Washing Machine',
    'Mattress',
    'Micromatic Induction Cooker',
    'Micromatic Iron',
    'Micromatic Washing Machine',
    'Midea Air Conditioner',
    'Midea Aircon',
    'Midea Microwave',
    'Mountain Bike',
    'Move IT Jersey',
    'Move It Helmet',
    'Move it Vest',
    'Nike Backpack',
    'Nike Bag',
    'Nike Leggings',
    'Nike Tote Bag',
    'Office Chair',
    'Organizer Rack',
    'Oven',
    'Panasonic Air Conditioner',
    'Panasonic Freezer',
    'Panasonic Water Heater',
    'Polo Shirt',
    'Queen bed',
    'Reception gown',
    'Refrigerator',
    'Roller Skates',
    'Romper',
    'Rusi Motorcycle',
    'Samsung Air Conditioner',
    'Samsung Automatic Washing Machine',
    'Samsung Refrigerator',
    'Samsung Washing Machine',
    'Sanden Freezer',
    'Sandwich Maker',
    'Sharp Washing Machine',
    'Shelves',
    'Shirts',
    'Shoe Cabinet',
    'Short',
    'Shorts',
    'Skateboard',
    'Skirt',
    'Sling Bag',
    'Sofa',
    'Sofabed',
    'Stoneware Plates',
    'Stroller',
    'Study Table',
    'Sweater',
    'T-shirt',
    'TCL Air Conditioner',
    'TCL Aircon',
    'TCL Automatic Washing Machine',
    'TCL Window Type Air Conditioner',
    'Toshiba Automatic Washing Machine',
    'Toy Lot',
    'Trench Coat',
    'Tyler Air Conditioner',
    'Unit',
    'Vest',
    'Vivo Smartphone',
    'Whirlpool Washing Machine',
    'Whiteboard',
    'Wood set',
    // Found live 2026-08-29, second pass with an expanded brand dictionary
    // (fast-fashion/footwear/furniture retailers weren't in the first pass's
    // brand-strip list, so e.g. "Uniqlo Clothing" fell through as
    // "non-generic" even though it's the same brand+bare-category problem as
    // "Samsung Refrigerator" above). Manually reviewed - all confirmed
    // brand-only with no specific style/model name (unlike e.g. "A.P.C.
    // Diane Rue Madame Tote Bag" or "Coach Mila Wallet", which ARE specific
    // enough to price and were deliberately left untouched).
    'Anello Sling Bag',
    'Bershka Clothing',
    'Bershka Heels',
    'Coach Bag',
    'Coach Purse',
    'Coach Sling Bag',
    'Coach Wallet',
    'Columbia Clothing',
    'Converse Shoes',
    'Converse Sneakers',
    'Fila Shoes',
    'GAP Hoodie',
    'H&M Blazer',
    'H&M Clothing',
    'H&M Pants',
    'H&M Sweater',
    'IKEA Bed',
    'IKEA Cabinet',
    'IKEA Mattress',
    'IKEA Sofa',
    'IKEA Table',
    'Kate Spade Sling Bag',
    'La Germania Gas Range',
    'La Germania Gas Stove',
    'La Germania Oven',
    'Longchamp Bag',
    'Lovito Clothes',
    'Mandaue Foam Bed Frame',
    'Mango Bag',
    'Outfit',
    'Plains and Prints Pants',
    'Plains and Prints Top',
    'Poco Phone',
    'Reebok Shoes',
    'Shein Clothes',
    'Shein Dress',
    'Shein Sandals',
    'Shein Top',
    'Skechers Shoes',
    'Uniqlo Clothing',
    'Uniqlo Dress',
    'Uniqlo Jeans',
    'Uniqlo Leggings',
    'Uniqlo Pants',
    'Uniqlo Polo Shirt',
    'Uniqlo Shirt',
    'Uniqlo T-Shirt',
    'Uniqlo Tops',
    'Uratex Bed',
    'Uratex Mattress',
    'Vans Shoes',
    'Zara Pants',
    'Zara Shorts',
    // Found live 2026-08-29 via detect-generic-products, reviewed and
    // applied (see generic-products.ts for the detector itself).
    'ASICS Shoes',
    'Air Fryer',
    'American Home Microwave',
    'American Home Washing Machine',
    'American Standard Toilet Bowl',
    'Asahi Ceiling Fan',
    'Asahi Stand Fan',
    'Astron Split Type Air Conditioner',
    'Battery',
    'Blouse',
    'Bluetooth Speaker',
    'Cabinet',
    'Cap',
    'Coach Tote Bag',
    'Condura Air Conditioner',
    'Condura Chest Freezer',
    'Condura Washing Machine',
    'Daikin Air Conditioner',
    'Dehumidifier',
    'Devant Speaker',
    'Fujidenzo Chest Freezer',
    'H&M Polo Shirt',
    'Haier Refrigerator',
    'Huawei Laptop',
    'IKEA Chair',
    'Ikea Backpack',
    'Imarflex Induction Cooker',
    'Jeans',
    'Kate Spade Tote Bag',
    'Kelvinator Refrigerator',
    'Kolin Water Dispenser',
    'LG Laptop',
    'MacBook',
    'MacBook Air',
    'MacBook Pro',
    'Micromatic Flat Iron',
    'Nike Shoes',
    'Onitsuka Tiger Shoes',
    'Panasonic Aircon',
    'Panasonic Refrigerator',
    'Panasonic Washing Machine',
    'Powerbank',
    'Realme Earbuds',
    'Realme Phone',
    'Rice Cooker',
    'Samsung Monitor',
    'Sharp Refrigerator',
    'Shirt',
    'Sony Earbuds',
    'TCL Mini Fridge',
    'TCL Refrigerator',
    'Top',
    'Treadmill',
    'Uniqlo Jacket',
    'Vacuum Cleaner',
    'Washing Machine',
    'Water Dispenser',
    'Water Heater',
    'Whirlpool Refrigerator',
    'Xiaomi Monitor',
    'Zara Blazer',
    'iPad',
    'iPad Air',
    'iPad Pro',
    'iPad mini',
    'iPhone',
    // moved from the real_estate list above - "lot" here means a bundle of
    // unrelated figures, not land (same shape as "Toy Lot" in an earlier
    // pass).
    'Action Figure Lot',
    'Action Figures Lot',
  ],
  // Unlike too_generic (no recoverable path — genuinely not a real, single
  // product), these ARE real, priceable products — they just need a pricing
  // strategy that doesn't exist yet: per-component pricing summed together
  // (see CONTEXT.md, 2026-08-23). Found live: "Gaming PC Set" returned a
  // "high confidence" ₱40,800-414,995 range, each number individually real
  // but grounded to totally different unrelated prebuilts, since a single
  // price range across arbitrary configurations is meaningless. Kept as a
  // distinct reason (not folded into too_generic) so this specific group is
  // queryable and can be revisited once that feature exists — query
  // `WHERE price_lookup_excluded_reason = 'needs_component_pricing'`.
  // 'CPU Motherboard Bundle'/'CPU Motherboard RAM Bundle' belong here too —
  // found live 2026-08-23: both returned the identical ₱4,895-58,140 (12x)
  // range, Exa clearly grounding to the general "PC parts bundle" market
  // rather than any specific bundle.
  needs_component_pricing: [
    'Desktop PC Setup',
    'Gaming PC Set',
    'Gaming PC Setup',
    'Gaming Setup',
    'PC Set',
    'Pre-built PC',
    'CPU Motherboard Bundle',
    'CPU Motherboard RAM Bundle',
    'AM4 System Unit',
    'Computer System Unit Core i5-7400',
    'Computer System Unit Core i7-4790',
    'Desktop System Unit',
    'Gaming PC System Unit',
    'Gaming System Unit',
    'PC System Unit',
    'PC Unit',
    'Ryzen 3 3200G System Unit',
    'Ryzen System Unit',
    // Found live 2026-08-23, same reason as 'Gaming PC Set' above - bare
    // 'Gaming PC'/'Desktop PC' bundle wildly different real builds (₱15-
    // ₱60,000 in the real listings) under one fake product.
    'Gaming PC',
    'Desktop PC',
  ],
  parts_accessory: [
    'Bicycle Accessories',
    'Bicycle Fork',
    'Bicycle Frame',
    'Bicycle Parts',
    'Bicycle Parts Bundle',
    'Camera Bag',
    'Camera Lens',
    'Car Audio Amplifier',
    'Car Audio System',
    'Car Fog Lamp',
    'Car Lights',
    'Car Part',
    'Car Seat',
    'Car Stereo',
    'Car Wheels',
    'Laptop Bag',
    'Laptop Cooler',
    'Laptop RAM',
    'Motorcycle Accessories',
    'Motorcycle Gas Tank',
    'Motorcycle Parts',
    'Motorcycle Raincoat',
    'Motorcycle Raincoat Suit',
    'Motorcycle Sidecar',
    'Motorcycle Top Box',
    'Motorcycle Wheel Mags',
    'Phone Case',
    'Phone Part',
    'Speaker Box',
    // Found live 2026-08-29, same broader scan - a component/accessory/
    // bundle, not a single priceable product (same reasoning as the
    // motorcycle/bicycle/laptop parts above).
    'Acer PC Case',
    'Acrylic Pastry Display Case',
    'Aerox Mags/Tires',
    'BF Goodrich Tires',
    'Bicycle Parts & Accessories',
    'Big Bike Tires',
    'Board Game Bundle',
    'Book & Manga Bundle',
    'Book Bundle',
    'Bridgestone Tire',
    'CPU, Motherboard & RAM Bundle',
    'CST Gravel Tires',
    'Camera Accessories',
    'Cat Wheel',
    'Clothes Bundle',
    'Clothing Bundle',
    'Computer Accessories',
    'Costume Accessories',
    'Croptop & Bundle Tops',
    'Desktop Computer Parts',
    'Die-cast Car Display Case',
    'E-Bike Battery & Parts',
    'E-bike Tire',
    'Electronics Accessories',
    'Furniture and Appliances Bundle',
    'General Grabber Tire',
    'Giant Tire',
    'Home Workout Equipment Bundle',
    'Honda SIR Wheels',
    'Matchbox Moving Parts',
    'Mio Engine Parts',
    'Motorcycle Part',
    'Nintendo Switch Accessories',
    'Nomatic Filter Case',
    'PC / Laptop Parts',
    'Pirelli Angel Tire',
    'Preloved Clothes Bundle',
    'Printer and Desktop PC Bundle',
    'Printer, Laminator, Cutter Bundle',
    'Prinx Tires',
    'Radiator cover and pair mole',
    'SJCAM Accessories & Modem',
    'Scaffolding Accessories',
    'Tech Bundle',
    'TineeOwl iPhone Case',
    'Two-Piece Swimsuit and Cover Up',
    'Vittoria Corsa Next TLR Tubeless Tires',
    'Westlake Tire',
    'Wheel and Rim',
    'Wheels & Tires',
    "Women's Clothes Bundle",
    // Found live 2026-08-29 via detect-generic-products, reviewed and
    // applied. "Case"/"Tire"/"Wheel" hints deliberately aren't exact-match
    // (unlike too_generic above) - a case/tire/wheel is treated as non-
    // singularly-priceable regardless of how specific its brand/model name
    // is, same convention as the original 'Phone Case'/'Car Wheels' entries
    // above (e.g. "Ground Zero VM-Grid PC Case" is a real named product, but
    // still excluded - a deliberate category-wide call, not a detector bug).
    'Aircon Bundle',
    'Appliance Bundle',
    'Best Flash Tires',
    'Black Mamba Rims with Tires',
    'Bridgestone Dueler HT Tires',
    'CVT Parts',
    'CVT Upgrade Parts',
    'Casetify iPhone Case',
    'Cellphones Bundle',
    'Computer Case',
    'Computer Parts Bundle',
    'Ground Zero VM-Grid PC Case',
    'Home Appliances Bundle',
    'Household Appliances & Furniture Bundle',
    'Household Items Bundle',
    'Kate Spade iPhone Case',
    'Kingston Computer Parts',
    'LAUT iPhone Air Case',
    'MTB Parts',
    'Mitsubishi Triton Wheels',
    'Mountainpeak Air Fork',
    'OtterBox React Case',
    'PC Case',
    'Panaracer Gravel King Tires',
    'Printer and Phone Bundle',
    'Quad Lock Case',
    'RAKK PC Case',
    'Rota Wheels',
    'Sim Racing Bundle',
    'Spigen Case',
    'Spigen Liquid Air Case',
    'Steering Wheel Arcade',
    'Tire',
    'Tire Sealant',
    'Tires',
    'Wanli Tires',
    'Wheel Set',
    'Zagg Pro Keyboard Case',
    'iPhone Case',
  ],
  service: [
    'Phone Upgrade Service',
    // Found live 2026-08-29, same broader scan - a service, not a resold
    // physical product.
    'Air Conditioner Buying Service',
    'Aircon Cleaning Service',
    'Appliance Buying Service',
    'Appliance Disposal Service',
    'Disposal Service',
    'Electronics Buying Service',
    'Hauling & Disposal Service',
    'Hauling Service',
    'Laptop Buying Service',
    'Make Up Manufacturing Service',
    'Massage Service',
    'RAM Buying Service',
    'Ride-sharing Service Jersey',
    'Scrap Battery Buying Service',
    'Scrap Buyer Service',
    'Scrap Buying Service',
    'Septic Tank/Drainage Cleaning Service',
    'TV Repair Service',
    // Found live 2026-08-29 via detect-generic-products, reviewed and applied.
    'Amplifier Service',
    'Financial Service',
    'PC Repair and Upgrade Service',
    'PCAB License Assistance Service',
    'Piso Wifi Setup Service',
    'Service',
  ],
}

// One excludeFromPricing write per reason in the curated list above.
export async function excludeIneligibleCategories(db: DbClient, logger: Logger): Promise<void> {
  // Object.entries widens keys to string; the record's type already pins them.
  for (const [reason, baseModels] of Object.entries(PRICE_INELIGIBLE_CATEGORIES) as [
    PriceExclusionReason,
    string[],
  ][]) {
    await excludeFromPricing(db, { baseModels }, reason)
    logger.info(`flagged ${baseModels.length} base_model values as '${reason}'`)
  }
}
