import type { SettingsCategory } from './settingsTypes'

export const WORKER_SETTINGS: SettingsCategory = {
  id: 'workers',
  label: 'Workers',
  subgroups: [
    {
      id: 'collect',
      title: 'collect',
      fields: [
        {
          key: 'collect.max_items_default',
          label: 'Max items per query',
          description: 'Default per-query item cap when no CLI arg is given.',
          unit: 'count',
          min: 1,
          defaultValue: 100,
        },
        {
          key: 'collect.soft_wall_timeout_ms',
          label: 'Soft-wall retry wait',
          description: 'How long to wait before retrying after a Facebook soft login-wall.',
          unit: 'ms',
          min: 1000,
          defaultValue: 5000,
        },
        {
          key: 'collect.pacing_min_ms',
          label: 'Pacing min (per listing)',
          description: 'Minimum random pause between opening listings during a live Facebook run.',
          unit: 'ms',
          min: 2000,
          defaultValue: 4000,
        },
        {
          key: 'collect.pacing_max_ms',
          label: 'Pacing max (per listing)',
          description: 'Maximum random pause between opening listings during a live Facebook run.',
          unit: 'ms',
          min: 2000,
          defaultValue: 10000,
        },
        {
          key: 'collect.loop_delay_ms',
          label: 'Loop delay',
          description:
            'Pause between laps (a full pass through the keyword list) in --cycle mode. Also how long the browser stays closed between laps, freeing it for check-listings to use.',
          unit: 'ms',
          min: 10000,
          defaultValue: 300000,
        },
        {
          key: 'collect.re_keywords_enabled',
          label: 'Real estate keywords',
          description: '1 = also run the real estate keyword pass; 0 = general keywords only (default).',
          unit: 'count',
          min: 0,
          defaultValue: 0,
        },
        {
          key: 'collect.re_every_n_laps',
          label: 'Real estate pass every N laps',
          description: 'The real estate keyword pass runs on lap 1 and every Nth lap after it.',
          unit: 'count',
          min: 1,
          defaultValue: 3,
        },
        {
          key: 'collect.re_max_items',
          label: 'Max items per real estate query',
          description: 'Per-query item cap during the real estate pass.',
          unit: 'count',
          min: 1,
          defaultValue: 50,
        },
      ],
    },
    {
      id: 'check_listings',
      title: 'check-listings',
      fields: [
        {
          key: 'check_listings.loop_delay_ms',
          label: 'Loop delay',
          description: 'Pause between laps.',
          unit: 'ms',
          min: 10000,
          defaultValue: 60000,
        },
        {
          key: 'check_listings.limit_default',
          label: 'Listings per lap',
          description: 'Default number of listings checked per lap when no CLI arg is given.',
          unit: 'count',
          min: 1,
          defaultValue: 100,
        },
        {
          key: 'check_listings.soft_wall_timeout_ms',
          label: 'Soft-wall retry wait',
          description:
            'How long to wait before retrying after a Facebook soft login-wall. Also used by the dashboard’s on-demand Refresh buttons.',
          unit: 'ms',
          min: 1000,
          defaultValue: 5000,
        },
        {
          key: 'check_listings.pacing_min_ms',
          label: 'Pacing min (per listing)',
          description: 'Minimum random pause between checking listings during a live Facebook run.',
          unit: 'ms',
          min: 2000,
          defaultValue: 2000,
        },
        {
          key: 'check_listings.pacing_max_ms',
          label: 'Pacing max (per listing)',
          description: 'Maximum random pause between checking listings during a live Facebook run.',
          unit: 'ms',
          min: 2000,
          defaultValue: 4000,
        },
        {
          key: 'check_listings.re_recheck_min_days',
          label: 'Real estate recheck spacing',
          description:
            'Skip real estate listings checked within this many days. 0 = no skipping (default). Other categories are unaffected.',
          unit: 'count',
          min: 0,
          defaultValue: 0,
        },
      ],
    },
    {
      id: 'extract_products',
      title: 'extract-products',
      fields: [
        {
          key: 'extract_products.max_attempts',
          label: 'Max attempts',
          description: 'Retry attempts per LLM provider before falling through/failing the batch.',
          unit: 'count',
          min: 1,
          defaultValue: 5,
        },
        {
          key: 'extract_products.retry_base_delay_ms',
          label: 'Retry base delay',
          description: 'Base delay for exponential backoff between retries.',
          unit: 'ms',
          min: 1000,
          defaultValue: 30000,
        },
        {
          key: 'extract_products.loop_delay_ms',
          label: 'Loop delay',
          description: 'Pause between laps.',
          unit: 'ms',
          min: 1000,
          defaultValue: 300000,
        },
        {
          key: 'extract_products.batch_size',
          label: 'Batch size',
          description: 'Listings sent to the LLM per extraction request.',
          unit: 'count',
          min: 1,
          defaultValue: 100,
        },
        {
          key: 'extract_products.inter_batch_delay_ms',
          label: 'Inter-batch delay',
          description: 'Pause between batches within a lap.',
          unit: 'ms',
          min: 1000,
          defaultValue: 5000,
        },
      ],
    },
    {
      id: 'enrich_products',
      title: 'enrich-products',
      fields: [
        {
          key: 'enrich_products.batch_size',
          label: 'Batch size',
          description: 'Products sent to the LLM per enrichment request.',
          unit: 'count',
          min: 1,
          defaultValue: 20,
        },
        {
          key: 'enrich_products.loop_delay_ms',
          label: 'Loop delay',
          description: 'Pause between laps.',
          unit: 'ms',
          min: 1000,
          defaultValue: 300000,
        },
        {
          key: 'enrich_products.max_attempts',
          label: 'Max attempts',
          description: 'Retry attempts on a malformed/failed batch response.',
          unit: 'count',
          min: 1,
          defaultValue: 3,
        },
        {
          key: 'enrich_products.retry_delay_ms',
          label: 'Retry delay',
          description: 'Fixed delay between retries.',
          unit: 'ms',
          min: 1000,
          defaultValue: 3000,
        },
      ],
    },
    {
      id: 'price_lookup',
      title: 'price-lookup',
      fields: [
        {
          key: 'price_lookup.lap_limit_default',
          label: 'Products per lap',
          description: 'Default number of products priced per lap when no CLI arg is given.',
          unit: 'count',
          min: 1,
          defaultValue: 20,
        },
        {
          key: 'price_lookup.loop_delay_ms',
          label: 'Loop delay',
          description: 'Pause between laps.',
          unit: 'ms',
          min: 1000,
          defaultValue: 300000,
        },
        {
          key: 'price_lookup.pacing_delay_ms',
          label: 'Pacing delay',
          description: 'Pause between products within a lap.',
          unit: 'ms',
          min: 1000,
          defaultValue: 1000,
        },
      ],
    },
    {
      id: 'enrich_listing_prices',
      title: 'enrich-listing-prices',
      fields: [
        {
          key: 'enrich_listing_prices.batch_size',
          label: 'Batch size',
          description: 'Listings sent to the LLM per price-review request.',
          unit: 'count',
          min: 1,
          defaultValue: 35,
        },
        {
          key: 'enrich_listing_prices.loop_delay_ms',
          label: 'Loop delay',
          description: 'Pause between laps.',
          unit: 'ms',
          min: 1000,
          defaultValue: 300000,
        },
      ],
    },
    {
      id: 'extract_real_estate',
      title: 'extract-real-estate',
      fields: [
        {
          key: 'extract_real_estate.batch_size',
          label: 'Batch size',
          description: 'Listings sent to the LLM per extraction request.',
          unit: 'count',
          min: 1,
          defaultValue: 10,
        },
        {
          key: 'extract_real_estate.loop_delay_ms',
          label: 'Loop delay',
          description: 'Pause between laps.',
          unit: 'ms',
          min: 1000,
          defaultValue: 300000,
        },
      ],
    },
    {
      id: 'verify_discount',
      title: 'verify-discount-notifications',
      fields: [
        {
          key: 'verify_discount.lap_limit_default',
          label: 'Paid-API candidates per lap',
          description: 'How many candidates draw against the paid Exa/Tavily/Gemini/OpenRouter budget per lap.',
          unit: 'count',
          min: 1,
          defaultValue: 3,
        },
        {
          key: 'verify_discount.fetch_batch_size',
          label: 'Rows fetched per lap',
          description: 'How many pending rows are pulled per lap (free prechecks run against all of them, uncapped).',
          unit: 'count',
          min: 1,
          defaultValue: 50,
        },
        {
          key: 'verify_discount.loop_delay_ms',
          label: 'Loop delay',
          description: 'Pause between laps.',
          unit: 'ms',
          min: 1000,
          defaultValue: 30000,
        },
        {
          key: 'verify_discount.pacing_delay_ms',
          label: 'Pacing delay',
          description: 'Pause between paid-API candidates within a lap.',
          unit: 'ms',
          min: 1000,
          defaultValue: 1000,
        },
      ],
    },
    {
      id: 'llm',
      title: 'LLM gateway',
      fields: [
        {
          key: 'llm.gateway_enabled',
          label: 'Use LLM gateway',
          description:
            '1 = JSON LLM calls go to the self-hosted gateway (llm.kber.dev) first, direct keys as fallback; 0 = direct keys only (default).',
          unit: 'count',
          min: 0,
          defaultValue: 0,
        },
      ],
    },
  ],
}
