import { fileURLToPath } from 'node:url'
import path from 'node:path'
import fs from 'node:fs'
import { Node, Project } from 'ts-morph'
import type { JSDocableNode } from 'ts-morph'

export interface ExtractedFunction {
  name: string
  signature: string
  description: string | null
  isClass: boolean
}

export interface ExtractedModule {
  path: string
  functions: ExtractedFunction[]
  imports: string[]
}

export interface ExtractedDomain {
  name: string
  modules: ExtractedModule[]
}

export interface ExtractedProject {
  name: string
  domains: ExtractedDomain[]
}

const defaultIsInRepoImport = (specifier: string) => specifier.startsWith('.')

export function extractArchitecture(
  project: Project,
  rootDir: string,
  pathPrefix: string,
  domainOf: (relPath: string) => string,
  isInRepoImport: (specifier: string) => boolean = defaultIsInRepoImport,
): ExtractedDomain[] {
  const modulesByDomain = new Map<string, ExtractedModule[]>()

  for (const sourceFile of project.getSourceFiles()) {
    const filePath = sourceFile.getFilePath()
    const relToRoot = path.posix.relative(rootDir.split(path.sep).join('/'), filePath)
    if (relToRoot.startsWith('..')) continue
    if (/\.test\.tsx?$/.test(relToRoot)) continue

    const functions = extractFunctions(sourceFile)
    if (functions.length === 0) continue

    const imports = sourceFile
      .getImportDeclarations()
      .map((imp) => imp.getModuleSpecifierValue())
      .filter(isInRepoImport)
      .sort()

    const modulePath = `${pathPrefix}/${relToRoot}`
    const domainName = domainOf(relToRoot)
    const list = modulesByDomain.get(domainName) ?? []
    list.push({ path: modulePath, functions, imports: [...new Set(imports)] })
    modulesByDomain.set(domainName, list)
  }

  return [...modulesByDomain.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, modules]) => ({
      name,
      modules: modules.sort((a, b) => a.path.localeCompare(b.path)),
    }))
}

function extractFunctions(sourceFile: ReturnType<Project['getSourceFiles']>[number]): ExtractedFunction[] {
  const results: ExtractedFunction[] = []
  for (const [name, declarations] of sourceFile.getExportedDeclarations()) {
    for (const decl of declarations) {
      const isClass = Node.isClassDeclaration(decl)
      const isFunctionLike =
        Node.isFunctionDeclaration(decl) || (Node.isVariableDeclaration(decl) && isFunctionInitializer(decl))

      if (!isClass && !isFunctionLike) continue

      results.push({
        name,
        signature: buildSignature(name, decl),
        description: getJsDocDescription(decl),
        isClass,
      })
    }
  }
  return results
}

function isFunctionInitializer(decl: Node): boolean {
  if (!Node.isVariableDeclaration(decl)) return false
  const init = decl.getInitializer()
  return init !== undefined && (Node.isArrowFunction(init) || Node.isFunctionExpression(init))
}

function buildSignature(name: string, decl: Node): string {
  if (Node.isClassDeclaration(decl)) return `class ${name}`

  let fn: Node | undefined
  if (Node.isFunctionDeclaration(decl)) fn = decl
  else if (Node.isVariableDeclaration(decl)) {
    const init = decl.getInitializer()
    if (init && (Node.isArrowFunction(init) || Node.isFunctionExpression(init))) fn = init
  }
  if (!fn || !Node.isFunctionLikeDeclaration(fn)) return name

  const params = fn
    .getParameters()
    .map((p) => p.getText())
    .join(', ')
  const returnTypeNode = fn.getReturnTypeNode()
  const returnType = returnTypeNode ? returnTypeNode.getText() : fn.getReturnType().getText()
  return oneLine(`${name}(${params}): ${returnType}`)
}

function oneLine(text: string): string {
  return text.replace(/\s+/g, ' ').trim()
}

function getJsDocDescription(decl: Node): string | null {
  let jsDocs: ReturnType<JSDocableNode['getJsDocs']> = []
  if (Node.isFunctionDeclaration(decl) || Node.isClassDeclaration(decl)) {
    jsDocs = decl.getJsDocs()
  } else if (Node.isVariableDeclaration(decl)) {
    const list = decl.getParent()
    const stmt = Node.isVariableDeclarationList(list) ? list.getParent() : undefined
    if (stmt && Node.isVariableStatement(stmt)) jsDocs = stmt.getJsDocs()
  }
  const description = jsDocs[0]?.getDescription().trim()
  return description ? description : null
}

export function slugify(domainName: string): string {
  return domainName.replace(/\//g, '-')
}

export function renderDomainMarkdown(projectName: string, domain: ExtractedDomain): string {
  const lines: string[] = [
    `# ${domain.name}`,
    '',
    `_Generated by \`scripts/gen-arch-doc.ts\` — do not hand-edit. Part of the \`${projectName}\` project._`,
    '',
  ]

  for (const module of domain.modules) {
    lines.push(`## ${module.path}`, '')
    if (module.imports.length > 0) {
      lines.push(`**Interactions:** imports ${module.imports.map((i) => `\`${i}\``).join(', ')}`, '')
    }
    for (const fn of module.functions) {
      lines.push(`### \`${fn.signature}\``, '')
      lines.push(fn.description ?? '_(undocumented)_', '')
    }
  }

  return lines.join('\n').trimEnd() + '\n'
}

export function renderProjectIndexMarkdown(project: ExtractedProject): string {
  const lines: string[] = [`# ${project.name}`, '']
  for (const domain of project.domains) {
    lines.push(`- [${domain.name}](./${slugify(domain.name)}.md)`)
  }
  return lines.join('\n').trimEnd() + '\n'
}

interface SiteManifest {
  projects: { name: string; domains: { name: string; slug: string }[] }[]
}

export function buildManifest(projects: ExtractedProject[]): SiteManifest {
  return {
    projects: projects.map((p) => ({
      name: p.name,
      domains: p.domains.map((d) => ({ name: d.name, slug: slugify(d.name) })),
    })),
  }
}

export function writeSite(projects: ExtractedProject[], outDir: string): void {
  fs.mkdirSync(outDir, { recursive: true })
  fs.writeFileSync(path.join(outDir, 'manifest.json'), JSON.stringify(buildManifest(projects), null, 2) + '\n')

  const indexLines = ['# Architecture', '', 'Auto-generated map of this app. Pick a project:', '']
  for (const project of projects) {
    const projectDir = path.join(outDir, project.name)
    fs.mkdirSync(projectDir, { recursive: true })
    fs.writeFileSync(path.join(projectDir, 'index.md'), renderProjectIndexMarkdown(project))
    for (const domain of project.domains) {
      fs.writeFileSync(path.join(projectDir, `${slugify(domain.name)}.md`), renderDomainMarkdown(project.name, domain))
    }
    indexLines.push(`- [${project.name}](./${project.name}/index.md)`)
  }
  fs.writeFileSync(path.join(outDir, 'index.md'), indexLines.join('\n').trimEnd() + '\n')
}

async function main() {
  const repoRoot = process.cwd()

  const srcProject = new Project({ tsConfigFilePath: path.join(repoRoot, 'tsconfig.json') })
  const serverProject = new Project({ tsConfigFilePath: path.join(repoRoot, 'server/tsconfig.json') })
  const dashboardProject = new Project({ tsConfigFilePath: path.join(repoRoot, 'dashboard/tsconfig.json') })

  const projects: ExtractedProject[] = [
    {
      name: 'src',
      domains: extractArchitecture(srcProject, path.join(repoRoot, 'src'), 'src', (relPath) => {
        const segments = relPath.split('/')
        return segments[0] === 'domains' && segments.length > 2 ? `${segments[0]}/${segments[1]}` : segments[0]
      }),
    },
    {
      name: 'server',
      domains: extractArchitecture(serverProject, path.join(repoRoot, 'server'), 'server', () => 'server'),
    },
    {
      name: 'dashboard',
      domains: extractArchitecture(
        dashboardProject,
        path.join(repoRoot, 'dashboard/src'),
        'dashboard/src',
        (relPath) => {
          const segments = relPath.split('/')
          return segments[0] === 'app' && segments.length > 2 ? `${segments[0]}/${segments[1]}` : segments[0]
        },
        (spec) => spec.startsWith('.') || spec.startsWith('@/'),
      ),
    },
  ]

  writeSite(projects, path.join(repoRoot, 'docs-site'))

  const undocumented = projects
    .flatMap((p) => p.domains)
    .flatMap((d) => d.modules)
    .flatMap((m) => m.functions)
    .filter((f) => f.description === null).length
  console.log(`docs-site/ written. ${undocumented} undocumented function(s)/class(es).`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  void main()
}
