// Copies the types and constants the dashboard shares with the feature modules
// into one generated dashboard file. The dashboard is its own package (own
// lockfile, deployed from dashboard/ as its root), so it can't import from
// src/ at build time without dragging the modules' SDK dependencies into its
// typecheck; a generated copy keeps one source of truth and the dashboard
// self-contained. Sources are read through each module's public index; the
// local types they reference come along even when the module keeps them internal.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { Node, Project, SyntaxKind } from 'ts-morph'
import prettier from 'prettier'

export const DASHBOARD_SHARED_PATH = 'dashboard/src/lib/shared.generated.ts'

interface SharedSource {
  index: string
  names: string[]
}

const SHARED_SOURCES: SharedSource[] = [
  { index: 'src/modules/real-estate/index.ts', names: ['RealEstateFilters', 'RealEstateListing'] },
  {
    index: 'src/modules/catalog/index.ts',
    names: [
      'PRODUCT_CATEGORIES',
      'ProductSummary',
      'SubCategoryTreeEntry',
      'ProductDetail',
      'ProductNeedingReview',
      'CategoryWeeklySoldCounts',
    ],
  },
  { index: 'src/modules/collection/index.ts', names: ['ListingDetail', 'SavedListingSummary', 'CollectKeyword'] },
  {
    index: 'src/modules/pricing/index.ts',
    names: [
      'DiscountBand',
      'ListingPriceReview',
      'SoldComparablePrice',
      'PeerMedianPrice',
      'ComparableListing',
      'DealListing',
      'DealsDiscountPolicyFloors',
      'DealsFilters',
      'DiscountNotification',
    ],
  },
  // Platform has no index; settings.ts is the settings feature's public file.
  { index: 'src/platform/settings.ts', names: ['SettingRow'] },
]

const HEADER = [
  '// @generated by scripts/gen-dashboard-shared.ts (pnpm gen-dashboard-shared). DO NOT EDIT.',
  '// Source of truth: the feature modules named below; change them and rerun the generator.',
]

export function loadModulesProject(repoRoot: string): Project {
  const project = new Project({
    tsConfigFilePath: path.join(repoRoot, 'tsconfig.json'),
    skipAddingFilesFromTsConfig: true,
  })
  for (const source of SHARED_SOURCES) project.addSourceFileAtPath(path.join(repoRoot, source.index))
  project.resolveSourceFileDependencies()
  return project
}

function declarationText(node: Node): string {
  const statement = Node.isVariableDeclaration(node) ? node.getVariableStatementOrThrow() : node
  const text = statement.getText()
  return text.startsWith('export ') ? text : `export ${text}`
}

function declarationName(node: Node): string {
  return Node.hasName(node) ? node.getName() : node.getText()
}

function isTopLevelValue(decl: Node): boolean {
  if (Node.isFunctionDeclaration(decl)) return Node.isSourceFile(decl.getParent())
  return Node.isVariableDeclaration(decl) && Node.isSourceFile(decl.getVariableStatement()?.getParent())
}

// Local declarations a declaration depends on, resolved through imports:
// interfaces/type aliases/enums its type references name, and module-level
// functions/constants its code uses (so a copied function keeps working).
// Library declarations (Date, Record, ...) live outside the project's own
// files and stay out.
function referencedDeclarations(node: Node): Node[] {
  const found: Node[] = []
  for (const id of node.getDescendantsOfKind(SyntaxKind.Identifier)) {
    let symbol = id.getSymbol()
    if (symbol?.isAlias()) symbol = symbol.getAliasedSymbol()
    for (const decl of symbol?.getDeclarations() ?? []) {
      if (decl === node || decl.getSourceFile().isInNodeModules() || decl.getSourceFile().isDeclarationFile()) continue
      const isType =
        Node.isInterfaceDeclaration(decl) || Node.isTypeAliasDeclaration(decl) || Node.isEnumDeclaration(decl)
      if (isType || isTopLevelValue(decl)) found.push(decl)
    }
  }
  return found
}

export async function renderDashboardShared(
  project: Project,
  sources: SharedSource[] = SHARED_SOURCES,
): Promise<string> {
  const sections: string[] = [HEADER.join('\n')]
  const emitted = new Map<string, Node>()
  // Depth-first so each type is followed by the ones it references (unless
  // already emitted); the dashboard gets one self-contained file. Two distinct
  // declarations under one name would silently shadow each other, so that fails.
  const emit = (node: Node) => {
    const name = declarationName(node)
    const existing = emitted.get(name)
    if (existing === node) return
    if (existing) throw new Error(`two declarations named ${name} would collide in ${DASHBOARD_SHARED_PATH}`)
    emitted.set(name, node)
    sections.push(declarationText(node))
    for (const dep of referencedDeclarations(node)) emit(dep)
  }
  for (const source of sources) {
    const indexFile = project.getSourceFileOrThrow((f) => f.getFilePath().endsWith(source.index.replace(/^\/?/, '/')))
    const exported = indexFile.getExportedDeclarations()
    sections.push(`// From ${source.index.replace(/^\//, '')}`)
    for (const name of source.names) {
      const [node] = exported.get(name) ?? []
      if (!node) throw new Error(`${source.index} does not export ${name}`)
      emit(node)
    }
  }
  const options = await prettier.resolveConfig(DASHBOARD_SHARED_PATH)
  return prettier.format(sections.join('\n\n'), { ...options, parser: 'typescript' })
}

async function main() {
  const repoRoot = process.cwd()
  const out = await renderDashboardShared(loadModulesProject(repoRoot))
  fs.writeFileSync(path.join(repoRoot, DASHBOARD_SHARED_PATH), out)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  void main()
}
